### PR TITLE
Remove FQCN-s

### PR DESCRIPTION
**Pull request by szepeviktor**
We are already in that: `namespace AdvertisingSettings;`
@leonstafford

### CODE REVIEW

**Comment by leonstafford** [comment]
Thanks for that @szepeviktor! Ah, this is what had me adjusting it yesterday:

```
FILE: ...Users/leon/coding-test-advertising-settings/advertising-settings.php
--------------------------------------------------------------------------
FOUND 0 ERRORS AND 6 WARNINGS AFFECTING 6 LINES
--------------------------------------------------------------------------
  35 | WARNING | Found unimported symbol 'Config'.
     |         | (ImportDetection.Imports.RequireImports.Symbol)
  40 | WARNING | Found unimported symbol 'Config'.
     |         | (ImportDetection.Imports.RequireImports.Symbol)
  68 | WARNING | Found unimported symbol 'Config'.
     |         | (ImportDetection.Imports.RequireImports.Symbol)
  79 | WARNING | Found unimported symbol 'Requirements'.
     |         | (ImportDetection.Imports.RequireImports.Symbol)
  93 | WARNING | Found unimported symbol 'registerCliCommands'.
     |         | (ImportDetection.Imports.RequireImports.Symbol)
 102 | WARNING | Found unimported symbol 'Config'.
     |         | (ImportDetection.Imports.RequireImports.Symbol)
     ```
     
 Are you seeing the same with `small-project`?

**Comment by leonstafford** [comment]
Ah, I see your [phpcs.xml](https://github.com/szepeviktor/small-project/blob/master/phpcs.xml) now!

**Comment by szepeviktor** [comment]
TIL :) https://github.com/sirbrillig/phpcs-import-detection/issues/45

**Comment by szepeviktor** [comment]
Look! https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesusefromsamenamespace- 👀

**Pull request merged**
